-- =============================================================================
-- Dapper Best Practice (.NET 4.6 + MySQL) — 既有系統整合資料表
-- =============================================================================
-- 本檔案收錄既有系統的資料表定義，若您的環境已存在這些資料表，可跳過本檔。
-- 其中 lots_info 為核心資料表的外鍵依賴，必須於執行 schema.sql 前存在。
--
-- 使用方式：
--   1. 若為全新環境，請先執行本檔建立整合資料表
--   2. 再執行 schema.sql 建立核心 9 張表
-- =============================================================================

CREATE TABLE `db_key` (
  `id` int NOT NULL AUTO_INCREMENT,
  `datetime` int DEFAULT NULL,
  `db_key` varchar(255) DEFAULT NULL,
  `recovery_rate` tinyint NOT NULL DEFAULT '0',
  `tester` tinyint NOT NULL DEFAULT '0',
  `test_result` tinyint NOT NULL DEFAULT '0',
  `fail_pin` tinyint NOT NULL DEFAULT '0',
  `check_status` tinyint NOT NULL DEFAULT '0',
  `import_status` tinyint NOT NULL DEFAULT '0',
  `mail` tinyint NOT NULL DEFAULT '0',
  `remark` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `db_key_ui_status` (
  `id` int NOT NULL AUTO_INCREMENT,
  `datetime` int DEFAULT NULL,
  `db_key` varchar(255) DEFAULT NULL,
  `ui_status` tinyint NOT NULL DEFAULT '0',
  `check_status` tinyint NOT NULL DEFAULT '0',
  `import_status` tinyint NOT NULL DEFAULT '0',
  `mail` tinyint NOT NULL DEFAULT '0',
  `remark` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fail_pin_rate_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `mac_address` varchar(20) DEFAULT NULL,
  `db_key` varchar(255) DEFAULT NULL COMMENT 'db_version',
  `area` varchar(20) DEFAULT NULL,
  `factory` varchar(20) DEFAULT NULL,
  `os_machine` varchar(20) DEFAULT NULL,
  `ao_lot` varchar(50) DEFAULT NULL,
  `mode` varchar(20) DEFAULT NULL,
  `data_format` varchar(10) DEFAULT NULL,
  `file_name` varchar(50) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `total` int DEFAULT NULL,
  `pass` int DEFAULT NULL,
  `open` int DEFAULT NULL,
  `short` int DEFAULT NULL,
  `lk` int DEFAULT NULL,
  `nVTEP` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_FAIL_PIN_RATE_INFO_DB_KEY` (`db_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fail_pin_rate_list` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fail_pin_rate_info_id` int DEFAULT NULL,
  `dut` int DEFAULT NULL,
  `sn_num` varchar(50) DEFAULT NULL,
  `site` int DEFAULT NULL,
  `fail_type` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fail_pin_rate_list_fail_pin_rate_info_id` (`fail_pin_rate_info_id`),
  CONSTRAINT `fail_pin_rate_list_fail_pin_rate_info` FOREIGN KEY (`fail_pin_rate_info_id`) REFERENCES `fail_pin_rate_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fail_pin_rate_list_pin_ball` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fail_pin_rate_list_id` int DEFAULT NULL,
  `pin` varchar(100) DEFAULT NULL,
  `ball` varchar(10) DEFAULT NULL,
  `remark` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fail_pin_rate_list_pin_ball_fail_pin_rate_list_id` (`fail_pin_rate_list_id`),
  CONSTRAINT `fail_pin_rate_list_pin_ball_fail_pin_rate_list` FOREIGN KEY (`fail_pin_rate_list_id`) REFERENCES `fail_pin_rate_list` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fail_pin_rate_test_result` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fail_pin_rate_list_id` int DEFAULT NULL,
  `item_name` varchar(50) DEFAULT '',
  `open` double DEFAULT NULL,
  `short` double DEFAULT NULL,
  `vmeas` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fail_pin_rate_test_result_fail_pin_rate_list_id` (`fail_pin_rate_list_id`),
  CONSTRAINT `fail_pin_rate_test_result_fail_pin_rate_list` FOREIGN KEY (`fail_pin_rate_list_id`) REFERENCES `fail_pin_rate_list` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ieda_content` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title_id` int DEFAULT NULL,
  `touch_down` int DEFAULT NULL,
  `sw_bin` int DEFAULT NULL,
  `vi_result` int DEFAULT NULL,
  `site_index` int DEFAULT NULL,
  `index_time` double DEFAULT NULL,
  `test_time` double DEFAULT NULL,
  `re_probing_flag_retest_flag` int DEFAULT NULL,
  `handler_arm` int DEFAULT NULL,
  `temperature` varchar(8) DEFAULT '',
  `package_start_time` datetime DEFAULT NULL,
  `handler_arm_force` double DEFAULT NULL,
  `wafer_id` varchar(12) DEFAULT '',
  `wafer_x` varchar(4) DEFAULT '',
  `wafer_y` varchar(4) DEFAULT '',
  `serial_number` int DEFAULT NULL,
  `efuse_string_1` varchar(53) DEFAULT '',
  `efuse_string_2` varchar(64) DEFAULT '',
  `efuse_string_3` varchar(46) DEFAULT '',
  `efuse_string_4` varchar(37) DEFAULT '',
  `spare_para_1` varchar(6) DEFAULT '',
  `spare_para_2` varchar(6) DEFAULT '',
  `spare_para_3` varchar(6) DEFAULT '',
  `spare_para_4` varchar(20) DEFAULT '',
  `soft_bin_name` varchar(20) DEFAULT '',
  `hard_bin_number` int DEFAULT NULL,
  `hard_bin_name` varchar(20) DEFAULT '',
  `ocr_laser_mark_qr_code` varchar(25) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `ieda_content_title_id` (`title_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ieda_title` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ase_lot` varchar(30) DEFAULT '',
  `lot_id` varchar(30) DEFAULT '',
  `sub_lot` varchar(2) DEFAULT '',
  `device` varchar(32) DEFAULT '',
  `mpw_code` varchar(4) DEFAULT '',
  `produce_code` varchar(6) DEFAULT '',
  `tester_id` varchar(8) DEFAULT '',
  `oper_id` varchar(8) DEFAULT '',
  `test_program` varchar(50) DEFAULT '',
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `socket_lid` varchar(12) DEFAULT '',
  `load_board_id` varchar(12) DEFAULT '',
  `bd_file` varchar(20) DEFAULT '',
  `package_notch` varchar(1) DEFAULT '',
  `sort_stage` varchar(1) DEFAULT '',
  `test_site` varchar(8) DEFAULT '',
  `fd_file` varchar(20) DEFAULT '',
  `cover_id_side_blade` varchar(20) DEFAULT '',
  `socket_id` varchar(20) DEFAULT '',
  `handler_id` varchar(20) DEFAULT '',
  `device_rev` varchar(10) DEFAULT '',
  `tsmc_lot_id` varchar(12) DEFAULT '',
  `assembly_start_date` varchar(11) DEFAULT '',
  `assembly_end_date` varchar(11) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `ieda_title_ase_lot` (`ase_lot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `lots_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `version` varchar(255) DEFAULT NULL,
  `mac_address` varchar(255) DEFAULT NULL,
  `db_key` varchar(255) DEFAULT NULL,
  `customer` varchar(255) DEFAULT NULL,
  `package` varchar(255) DEFAULT NULL,
  `bonding_diagram` varchar(255) DEFAULT NULL,
  `program` varchar(255) DEFAULT NULL,
  `device` varchar(255) DEFAULT NULL,
  `control_lot` varchar(255) DEFAULT NULL,
  `ao_lot` varchar(255) DEFAULT NULL,
  `os_machine_id` varchar(255) DEFAULT NULL,
  `os_test_board_id` varchar(255) DEFAULT NULL,
  `user_id` varchar(255) DEFAULT NULL,
  `schedule_lot` varchar(255) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `yield` double DEFAULT NULL,
  `total` int DEFAULT NULL,
  `pass` int DEFAULT NULL,
  `open_pin_fail` int DEFAULT NULL,
  `short_pin_fail` int DEFAULT NULL,
  `leakage_pin_fail` int DEFAULT NULL,
  `nvtep_pin_fail` int DEFAULT NULL,
  `total_ppm` double DEFAULT NULL,
  `open_pin_fail_ppm` double DEFAULT NULL,
  `short_pin_fail_ppm` double DEFAULT NULL,
  `leakage_pin_fail_ppm` double DEFAULT NULL,
  `nvtep_pin_fail_ppm` double DEFAULT NULL,
  `total_test_items` int DEFAULT NULL,
  `average_test_time` double DEFAULT NULL,
  `clear_count` double DEFAULT NULL,
  `start` datetime DEFAULT NULL,
  `stop` datetime DEFAULT NULL,
  `pass_without_ocr` int DEFAULT NULL,
  `open` int DEFAULT NULL,
  `open_without_ocr` int DEFAULT NULL,
  `short_others` int DEFAULT NULL,
  `pass_without_ocr_ppm` double DEFAULT NULL,
  `open_ppm` double DEFAULT NULL,
  `open_without_ocr_ppm` double DEFAULT NULL,
  `short_others_ppm` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `file_name` (`file_name`),
  KEY `IDX_LOTS_INFO_DB_KEY` (`db_key`),
  KEY `idx_program` (`program`),
  KEY `idx_customer ` (`customer`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `lots_result` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `lot_id` int DEFAULT NULL,
  `serial` int DEFAULT NULL,
  `retest_loc` varchar(2) NOT NULL DEFAULT '',
  `sn_num` varchar(50) DEFAULT NULL,
  `site_id` int DEFAULT NULL,
  `x` int DEFAULT NULL,
  `y` int DEFAULT NULL,
  `hbin` varchar(30) DEFAULT NULL,
  `pass/fail` enum('pass','fail') DEFAULT NULL,
  `test_time` double DEFAULT NULL,
  `index_time` double DEFAULT NULL,
  `real_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `lot_id` (`lot_id`),
  CONSTRAINT `lots_result_ibfk_1` FOREIGN KEY (`lot_id`) REFERENCES `lots_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `lots_statistic` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `lot_id` int DEFAULT NULL,
  `site_id` int DEFAULT NULL,
  `item_no` int DEFAULT NULL,
  `item_name` varchar(50) DEFAULT '',
  `net_name` varchar(50) DEFAULT '',
  `force` double DEFAULT NULL,
  `wait_time` double DEFAULT NULL,
  `spec_max` double DEFAULT NULL,
  `spec_min` double DEFAULT NULL,
  `pass` int DEFAULT NULL,
  `pass_n` int DEFAULT NULL,
  `fail` int DEFAULT NULL,
  `min` double DEFAULT NULL,
  `max` double DEFAULT NULL,
  `avg` double DEFAULT NULL,
  `avg_2` double DEFAULT NULL COMMENT '平方和平均',
  `stdev` double DEFAULT NULL,
  `cp` double DEFAULT NULL,
  `cpk` double DEFAULT NULL,
  `unit` varchar(20) DEFAULT '',
  `value` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `lots_statistic_lot_id` (`lot_id`),
  KEY `item_no` (`item_no`),
  CONSTRAINT `lots_statistic_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `lots_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `recovery_rate` (
  `id` int NOT NULL AUTO_INCREMENT,
  `db_key` varchar(255) DEFAULT NULL,
  `area` varchar(20) DEFAULT NULL,
  `factory` varchar(20) DEFAULT NULL,
  `os_machine` varchar(20) DEFAULT NULL,
  `customer` varchar(20) DEFAULT NULL,
  `program` varchar(255) DEFAULT NULL,
  `ao_lot` varchar(20) DEFAULT NULL,
  `mode` varchar(20) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `test_item` varchar(50) DEFAULT NULL,
  `defect_mode` varchar(20) DEFAULT NULL,
  `re_test_pass` varchar(20) DEFAULT NULL,
  `fail_pin_count` int DEFAULT '0',
  `total_unit` int DEFAULT '0',
  `recovery_rate` double DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `IDX_RECOVERY_RATE_DB_KEY` (`db_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tester_device_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `db_key` varchar(255) DEFAULT 'N/A',
  `mac_address` varchar(20) DEFAULT NULL,
  `ip_address` varchar(20) DEFAULT NULL,
  `area` varchar(50) DEFAULT NULL,
  `factory` varchar(20) DEFAULT NULL,
  `machine_type` varchar(20) DEFAULT NULL,
  `machine_id` varchar(50) DEFAULT NULL,
  `customer` varchar(20) DEFAULT NULL,
  `device_production` varchar(50) DEFAULT NULL,
  `device_engineer` varchar(50) DEFAULT NULL,
  `test_program` varchar(255) DEFAULT NULL,
  `program_path` varchar(255) DEFAULT NULL,
  `lot_id` varchar(50) DEFAULT NULL,
  `wafer_id` varchar(50) DEFAULT NULL,
  `execution_mode` varchar(20) DEFAULT NULL,
  `prober/handler` varchar(50) DEFAULT NULL,
  `L/B_id` varchar(50) DEFAULT NULL,
  `dut_board_type` varchar(20) DEFAULT NULL,
  `efficiency_check` int DEFAULT NULL,
  `ui_flow_checksum` int DEFAULT NULL,
  `yield` double DEFAULT NULL,
  `file_type` varchar(20) DEFAULT NULL,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `lead_count` int DEFAULT NULL,
  `site_qty` int DEFAULT NULL,
  `bd_leak` int DEFAULT NULL,
  `pg_leak` int DEFAULT NULL,
  `wireclose_leak` int DEFAULT NULL,
  `handler_type` varchar(20) DEFAULT NULL,
  `handler_sw_version` varchar(20) DEFAULT NULL,
  `handler_repair_start_time` varchar(20) DEFAULT NULL,
  `handler_repair_end_time` varchar(20) DEFAULT NULL,
  `doe_flag` int DEFAULT NULL,
  `hso_mode` varchar(50) DEFAULT NULL,
  `mp_api_log` int DEFAULT NULL,
  `mp_tt_log` int DEFAULT NULL,
  `smart_delay_enable` int DEFAULT NULL,
  `smart_delay_time` double DEFAULT NULL,
  `atv_information` int DEFAULT '0',
  `NetlistInfo` int DEFAULT NULL,
  `TP_CheckerDetectionResults` int DEFAULT NULL,
  `PG_LeakageEnabled` int DEFAULT NULL,
  `LeakageEnabled` int DEFAULT NULL,
  `EnhanceTestTtemQTY` int DEFAULT NULL,
  `First_Yield` double DEFAULT NULL,
  `shortFailAnalysisFlag` int DEFAULT NULL,
  `OSVersion` varchar(50) DEFAULT NULL,
  `DCT_Type` varchar(50) DEFAULT NULL,
  `DCT_Qty` int DEFAULT NULL,
  `DCT_CH_Qty` int DEFAULT NULL,
  `LB_Type` varchar(50) DEFAULT NULL,
  `ConnecterType` varchar(50) DEFAULT NULL,
  `Short_Plate_Check_Status` varchar(64) DEFAULT NULL,
  `Short_Plate_Check_Pin_qty_match` varchar(16) DEFAULT NULL,
  `TP_HighRiskLot` int DEFAULT NULL,
  `TP_WarningLot` int DEFAULT NULL,
  `TP_OverkillQTY` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_TESTER_DEVICE_INFO_DB_KEY` (`db_key`),
  KEY `idx_test_program` (`test_program`),
  KEY `idx_customer ` (`customer`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tester_production_analysis` (
  `id` int NOT NULL AUTO_INCREMENT,
  `device_info_id` int DEFAULT NULL,
  `site1_yield` double DEFAULT NULL,
  `site2_yield` double DEFAULT NULL,
  `site3_yield` double DEFAULT NULL,
  `site4_yield` double DEFAULT NULL,
  `site5_yield` double DEFAULT NULL,
  `site6_yield` double DEFAULT NULL,
  `site7_yield` double DEFAULT NULL,
  `site8_yield` double DEFAULT NULL,
  `site9_yield` double DEFAULT NULL,
  `site10_yield` double DEFAULT NULL,
  `site11_yield` double DEFAULT NULL,
  `site12_yield` double DEFAULT NULL,
  `site13_yield` double DEFAULT NULL,
  `site14_yield` double DEFAULT NULL,
  `site15_yield` double DEFAULT NULL,
  `site16_yield` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tester_device_info_tester_production_analysis` (`device_info_id`),
  CONSTRAINT `tester_device_info_tester_production_analysis` FOREIGN KEY (`device_info_id`) REFERENCES `tester_device_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tester_status` (
  `id` int NOT NULL AUTO_INCREMENT,
  `device_info_id` int DEFAULT NULL,
  `dpw` varchar(20) DEFAULT NULL,
  `duts` int DEFAULT NULL,
  `csv_name` varchar(100) DEFAULT NULL,
  `uph` double DEFAULT NULL,
  `avg_test_time` double DEFAULT NULL,
  `max_test_time` double DEFAULT NULL,
  `min_test_time` double DEFAULT NULL,
  `avg_index_test_time` double DEFAULT NULL,
  `max_index_test_time` double DEFAULT NULL,
  `min_index_test_time` double DEFAULT NULL,
  `diff_time_die` double DEFAULT NULL,
  `end_time_die` double DEFAULT NULL,
  `first_time_die` double DEFAULT NULL,
  `diff_time_file` double DEFAULT NULL,
  `conclusion_file_path` varchar(255) DEFAULT NULL,
  `raw_date_file_path` varchar(255) DEFAULT NULL,
  `s2s_diff_file_path` varchar(255) DEFAULT NULL,
  `pass/fail` enum('pass','fail') DEFAULT NULL,
  `case_a_result` varchar(20) DEFAULT NULL,
  `case_b_result` varchar(20) DEFAULT NULL,
  `case_c_result` varchar(20) DEFAULT NULL,
  `pui_result` varchar(20) DEFAULT NULL,
  `pui_respond` varchar(255) DEFAULT NULL,
  `pui_file_type` varchar(20) DEFAULT NULL,
  `phi_result` varchar(20) DEFAULT NULL,
  `phi_respond` varchar(255) DEFAULT NULL,
  `phi_file_type` varchar(20) DEFAULT NULL,
  `tp_result` varchar(20) DEFAULT NULL,
  `tp_respond` varchar(100) DEFAULT NULL,
  `manual_data_module_csv_g_result` varchar(20) DEFAULT NULL,
  `manual_data_module_csv_g_respond` varchar(20) DEFAULT NULL,
  `data_module_stdf_g_result` varchar(20) DEFAULT NULL,
  `data_module_stdf_g_respond` varchar(20) DEFAULT NULL,
  `data_module_txt_g_result` varchar(20) DEFAULT NULL,
  `data_module_txt_g_respond` varchar(20) DEFAULT NULL,
  `data_module_std_g_result` varchar(20) DEFAULT NULL,
  `data_module_std_g_respond` varchar(20) DEFAULT NULL,
  `test_time_module_csv_g_result` varchar(20) DEFAULT NULL,
  `test_time_module_csv_g_respond` varchar(20) DEFAULT NULL,
  `data_module_act_smart1_txt_result` varchar(20) DEFAULT NULL,
  `data_module_act_smart1_txt_respond` varchar(20) DEFAULT NULL,
  `data_module_asekh_smart1_xml_result` varchar(100) DEFAULT NULL,
  `data_module_asekh_smart1_xml_respond` varchar(255) DEFAULT NULL,
  `data_module_act_fail_log_result` varchar(20) DEFAULT NULL,
  `data_module_act_fail_log_respond` varchar(20) DEFAULT NULL,
  `vim_result` varchar(20) DEFAULT NULL,
  `vim_respond` varchar(20) DEFAULT NULL,
  `vim_open_result` varchar(20) DEFAULT NULL,
  `vim_open_respond` varchar(20) DEFAULT NULL,
  `vicbit_result` varchar(20) DEFAULT NULL,
  `vicbit_respond` varchar(20) DEFAULT NULL,
  `vicbit_open_result` varchar(20) DEFAULT NULL,
  `vicbit_open_respond` varchar(20) DEFAULT NULL,
  `pattern_result` varchar(20) DEFAULT NULL,
  `pattern_respond` varchar(20) DEFAULT NULL,
  `SWT_result` varchar(20) DEFAULT NULL,
  `SWT_respond` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tester_device_info_tester_status` (`device_info_id`),
  CONSTRAINT `tester_device_info_tester_status` FOREIGN KEY (`device_info_id`) REFERENCES `tester_device_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tester_sw_version` (
  `id` int NOT NULL AUTO_INCREMENT,
  `device_info_id` int DEFAULT NULL,
  `pui_version` varchar(20) DEFAULT NULL,
  `library_version` varchar(50) DEFAULT NULL,
  `virtual_instrument_version` varchar(50) DEFAULT NULL,
  `mingw_version` varchar(20) DEFAULT NULL,
  `all_md5_checksum` varchar(20) DEFAULT NULL,
  `auto_learn_ui_md5` varchar(32) DEFAULT NULL,
  `dct_product_file_setting_ui_md5` varchar(32) DEFAULT NULL,
  `dct_login_ui_md5` varchar(32) DEFAULT NULL,
  `os_self_diag_2k_md5` varchar(32) DEFAULT NULL,
  `pattonkan_ui_md5` varchar(32) DEFAULT NULL,
  `dct_iv_curve_tool_md5` varchar(32) DEFAULT NULL,
  `os_tester_100ma_vi_md5` varchar(32) DEFAULT NULL,
  `os_tester_2a_vi_md5` varchar(32) DEFAULT NULL,
  `os_tester_lcr_meter_md5` varchar(32) DEFAULT NULL,
  `wire_assignment_tool_md5` varchar(32) DEFAULT NULL,
  `bga_highlight_tool_md5` varchar(32) DEFAULT NULL,
  `simplification_ui_md5` varchar(32) DEFAULT NULL,
  `os_scan_tool_md5` varchar(32) DEFAULT NULL,
  `dct_uploadtp_ui_md5` varchar(32) DEFAULT NULL,
  `dct_autodownloadtp_md5` varchar(32) DEFAULT NULL,
  `autolearn_dll_md5` varchar(32) DEFAULT NULL,
  `integration_simplified_tp_lib_dll_md5` varchar(32) DEFAULT NULL,
  `libpublic_module_dll_md5` varchar(32) DEFAULT NULL,
  `liblpsa_libs_dll_md5` varchar(32) DEFAULT NULL,
  `libvim_total_libs_dll_md5` varchar(32) DEFAULT NULL,
  `slot0_dll_md5` varchar(32) DEFAULT NULL,
  `libtid_mem_libs_dll_md5` varchar(32) DEFAULT NULL,
  `sys_tid_libs_dll_md5` varchar(32) DEFAULT NULL,
  `confirm_ftp_upload_dll_md5` varchar(32) DEFAULT NULL,
  `confirm_ftp_upload_g_dll_md5` varchar(32) DEFAULT NULL,
  `ctp_hontech_ttl_phi_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_asecl_assy_csv_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_asecl_fail_log_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_asecl_smart1_txt_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_asekh_a5_csv_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_asekh_a5_summary_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_asekh_change_kit_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_asekh_recoverrate_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_asekh_smart1_txt_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_asekh_smart1_xml_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_assy_txt_g_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_ca_csv_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_create_spec_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_csv_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_csv_g_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_intime_summary_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_std_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_stdf_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_stdf_g_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_std_g_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_txt_dll_md5` varchar(32) DEFAULT NULL,
  `data_module_txt_g_dll_md5` varchar(32) DEFAULT NULL,
  `hello_phi_dll_md5` varchar(32) DEFAULT NULL,
  `high_light_sys_dll_md5` varchar(32) DEFAULT NULL,
  `hontech_phi_dll_md5` varchar(32) DEFAULT NULL,
  `k2_150a_dll_md5` varchar(32) DEFAULT NULL,
  `manual_data_module_csv_g_dll_md5` varchar(32) DEFAULT NULL,
  `secs_gem_connect_dll_md5` varchar(32) DEFAULT NULL,
  `srm_phi_dll_md5` varchar(32) DEFAULT NULL,
  `tel_p12_phi_dll_md5` varchar(32) DEFAULT NULL,
  `test_time_module_csv_g_dll_md5` varchar(32) DEFAULT NULL,
  `rf_offset_data_module_csv_g_dll_md5` varchar(32) DEFAULT NULL,
  `2g_pat_module_inprocess_dma_dll_md5` varchar(32) DEFAULT NULL,
  `2g_multi_process_dll_md5` varchar(32) DEFAULT NULL,
  `auto_learn_pui_version` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tester_device_info_tester_sw_version` (`device_info_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ui_status` (
  `id` int NOT NULL AUTO_INCREMENT,
  `mac_address` varchar(50) DEFAULT NULL,
  `area` varchar(50) DEFAULT NULL,
  `factory` varchar(10) DEFAULT NULL,
  `os_machine` varchar(50) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `auto_learn` int DEFAULT NULL,
  `dct_product_file_setting_ui` int DEFAULT NULL,
  `dct_login_ui` int DEFAULT NULL,
  `os_self_diag_2k` int DEFAULT NULL,
  `pattonkan_ui` int DEFAULT NULL,
  `dct_i_v_curve_tool` int DEFAULT NULL,
  `os_tester_100ma_vi` int DEFAULT NULL,
  `os_tester_2a_vi` int DEFAULT NULL,
  `os_tester_lcr_meter` int DEFAULT NULL,
  `wire_assignment_tool` int DEFAULT NULL,
  `bga_highlight_tool` int DEFAULT NULL,
  `simplificationui` int DEFAULT NULL,
  `os_scan_tool` int DEFAULT NULL,
  `dct_uploadtp_ui` int DEFAULT NULL,
  `dct_autodownloadtp` int DEFAULT NULL,
  `dct_sw_control_tool` int DEFAULT NULL,
  `dct_downloadtp_kh` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
